---
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/fuzzy-repo-finder/main.go
archive:
  format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^Docs:'
      - '^Test:'
      - '^Update readme'
      - '^Update readme.*'
