---
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/hoto/fuzzy-repo-finder
    steps:
      - checkout
      - run: make dependencies
      - run: make test
  release:
    docker:
      - image: circleci/golang:1.11.3
    steps:
      - checkout
      - run: make dependencies
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
